source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "webrick"
gem "ffi", "1.15.5"
gem "public_suffix", "~> 4.0"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "kramdown-parser-gfm"
gem "jekyll-sass-converter"
